"""Ports de persistance (DATA-1.2) — Protocols implémentés par l'infrastructure.

Les cas d'usage dépendent de ces interfaces, jamais de SQLAlchemy. Un fake in-memory
(tests) et l'implémentation Postgres (infrastructure) honorent le même contrat.
"""

from __future__ import annotations

from typing import Protocol

from app.domain.entities import (
    Account,
    ApiKey,
    FormDefinition,
    LiveSession,
    UsageRecord,
)


class AccountRepo(Protocol):
    async def add(self, account: Account) -> Account: ...
    async def get(self, account_id: int) -> Account | None: ...
    async def get_by_email(self, email: str) -> Account | None: ...
    async def list(self) -> list[Account]: ...
    async def update(self, account: Account) -> Account: ...


class ApiKeyRepo(Protocol):
    async def add(self, key: ApiKey) -> ApiKey: ...
    async def get_by_hash(self, key_hash: str) -> ApiKey | None: ...
    async def list_for_account(self, account_id: int) -> list[ApiKey]: ...
    async def revoke(self, key_id: int) -> ApiKey | None: ...


class FormRepo(Protocol):
    async def add(self, form: FormDefinition) -> FormDefinition: ...
    async def get(self, account_id: int, form_id: str) -> FormDefinition | None: ...
    async def list_for_account(self, account_id: int) -> list[FormDefinition]: ...
    async def update(self, form: FormDefinition) -> FormDefinition: ...


class SessionRepo(Protocol):
    async def add(self, session: LiveSession) -> LiveSession: ...
    async def get(self, session_id: str) -> LiveSession | None: ...
    async def update(self, session: LiveSession) -> LiveSession: ...


class UsageRepo(Protocol):
    async def record(self, usage: UsageRecord) -> UsageRecord: ...
    async def count_by_endpoint(self, account_id: int) -> dict[str, int]: ...
