"""schema initial

Revision ID: 41c43edd76dc
Revises: 
Create Date: 2026-06-24 14:27:44.901250
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '41c43edd76dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('email_contact', sa.String(length=255), nullable=False),
    sa.Column('langue', sa.String(length=2), nullable=False),
    sa.Column('persona_prompt', sa.Text(), nullable=False),
    sa.Column('voice_prompt', sa.Text(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_contact')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('cree_a', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_table('form_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.String(length=120), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('langue', sa.String(length=2), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'form_id', 'version', name='uq_form_version')
    )
    op.create_index(op.f('ix_form_definitions_form_id'), 'form_definitions', ['form_id'], unique=False)
    op.create_table('live_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.String(length=120), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('cree_a', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('horodatage', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_account_id'), 'usage_records', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_records_account_id'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_table('live_sessions')
    op.drop_index(op.f('ix_form_definitions_form_id'), table_name='form_definitions')
    op.drop_table('form_definitions')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('accounts')
    # ### end Alembic commands ###
