"""compte allowed_origins

Revision ID: 70002aa1f713
Revises: 41c43edd76dc
Create Date: 2026-06-24 16:12:54.728620
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '70002aa1f713'
down_revision: Union[str, None] = '41c43edd76dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default pour les lignes existantes (liste vide = aucune restriction d'origine).
    op.add_column(
        'accounts',
        sa.Column('allowed_origins', sa.JSON(), nullable=False, server_default='[]'),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'allowed_origins')
    # ### end Alembic commands ###
